version: "3"
services:
  nginx:
    build:
      context: ./frontend
      dockerfile: ./Devops/Dockerfile
    ports:
      - "80:80"
    restart: always
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always