export const EventTypesEnum = {
  american_football_match: "american_football_match",
  american_football_outright: "american_football_outright",
  baseball_match: "baseball_match",
  baseball_outright: "baseball_outright",
  basketball_esports_match: "basketball_esports_match",
  basketball_match: "basketball_match",
  boxing_match: "boxing_match",
  call_of_duty_match: "call_of_duty_match",
  cricket_match: "cricket_match",
  cricket_outright: "cricket_outright",
  csgo_match: "csgo_match",
  current_affairs: "current_affairs",
  cycling: "cycling",
  darts_match: "darts_match",
  darts_outright: "darts_outright",
  dota_2_match: "dota_2_match",
  football_esports_match: "football_esports_match",
  football_match: "football_match",
  football_outright: "football_outright",
  golf_match: "golf_match",
  golf_outright: "golf_outright",
  greyhound_racing_race: "greyhound_racing_race",
  handball_match: "handball_match",
  horse_racing_race: "horse_racing_race",
  ice_hockey_match: "ice_hockey_match",
  league_of_legends_match: "league_of_legends_match",
  mma_match: "mma_match",
  motorsports_race: "motorsports_race",
  motorsports_outright: "motorsports_outright",
  politics: "politics",
  politics_outright: "politics_outright",
  rowing: "rowing",
  rugby_league_match: "rugby_league_match",
  rugby_league_outright: "rugby_league_outright",
  rugby_union_match: "rugby_union_match",
  rugby_union_outright: "rugby_union_outright",
  sailing_race: "sailing_race",
  sailing_outright: "sailing_outright",
  snooker_match: "snooker_match",
  snooker_outright: "snooker_outright",
  table_tennis_match: "table_tennis_match",
  table_tennis_outright: "table_tennis_outright",
  tennis_match: "tennis_match",
  tennis_outright: "tennis_outright",
  volleyball_match: "volleyball_match",
  generic: "generic",
  top_level_event: "top_level_event",
  tv_entertainment: "tv_entertainment",
};
export const EventTypeList = Object.keys(EventTypesEnum).map((key) => {
  return { value: key, label: EventTypesEnum[key] };
});
